name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# This cancels older workflow runs on pull requests while ensuring that there
# are no concurrency limits on pushes and manual workflow dispatches.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 30

    runs-on: [self-hosted, x86_64-linux]

    steps:
      - uses: https://codeberg.org/ziglang/checkout@19af6bac491e2534a4687a50ee84fa7f13258d28

      - run: npm install
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run format:check

      - name: package extension
        run: |
          npx vsce package --baseContentUrl https://codeberg.org/ziglang/vscode-zig
          ls -lt *.vsix
