name: ci

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, x86_64-linux]
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run format:check

      - name: package extension
        run: |
          npx vsce package
          ls -lt *.vsix
