name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 30

    runs-on: [self-hosted, x86_64-linux]

    steps:
      - uses: https://codeberg.org/ziglang/checkout@19af6bac491e2534a4687a50ee84fa7f13258d28

      - run: npm install
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run format:check

      - name: package extension
        run: |
          npx vsce package --baseContentUrl https://codeberg.org/ziglang/vscode-zig
          ls -lt *.vsix
